name: Train Wake Word

on:
  workflow_dispatch:
    inputs:
      wake_word:
        type: string
        required: true

      model_name:
        type: string
        required: true

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run training container
        run: |
          mkdir -p ${{ github.workspace }}/out
          
          docker run \
            -v ${{ github.workspace }}/out:/out \
            helvio/mww \
            --train \
            --wake-word "${{ inputs.wake_word }}" \
            --model-name ${{ inputs.model_name }}

      - name: Upload trained model
        uses: actions/upload-artifact@v3
        with:
          name: glados-model
          path: ${{ github.workspace }}/out
