name: Notebook ausführen

on: 
  workflow_dispatch: {}

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Notebook ausführen
        uses: yaananth/run-notebook@v2
        with:
          notebook: 'notebooks/basic_training_notebook.ipynb'
          isReport: false

      - name: Artefakte hochladen
        uses: actions/upload-artifact@v3
        with:
          name: notebook-output
          path: ${{ runner.temp }}/nb-runner
